### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by RaiVaibhav** [deepgram-devs/deepgram-conversational-demo#29]
## Proposed changes

- Selecting model before `initialization`, give user an option to select the model?
- Text area with limited rows instead of input? right now if I press `shift+enter` then it acts as a enter
- Maintaining the state of chosen model on refresh?
- Mobile view fixes: logo image is too big (width wise) for small screen, if text messages are big then it doesn't break into another line?
- Performance optimization? (check the lighthouse)

## Context

Few of my initial findings, while I was on my phone. First thing I noticed after login into the Deepgram that it have different model, but there is no option to choose.

## Possible Implementation

> Not obligatory, but suggest an idea for implementing addition or change

## Other information

I would be happy to contribute.

**Comment by lukeocodes** [comment]
- model selection

on model selection, I'd quite like to have the deepgram connection occur after the app interface has loaded, and show a loading wheel while we connect to the websocket. that way, we can use the settings draw, and on changing model it will show the loading screen again.

hopefully this will give us the benefit of keeping message history while users are allowed to change whichever settings they wish

let's separate this into a separate issue so we can continue to discuss it.

- text area with limited rows instead of input

love this. would love a PR that maintains the mobile-friendly interface and allows multiple lines of input. 

go for it!

- refreshable state

for settings, yeh this is a great idea. i believe there are some nice solutions out there in the wild for syncing useState with localstorage. useLocalStorage might be done

go for it!

- mobile fixes

go for it!

- performance opt

go for it!

**Comment by RaiVaibhav** [comment]
Ack, I will create a separate issue for the first issue. 👍
